import React, { useEffect } from "react";
import { useRouter } from "next/router";
import Head from "next/head";
import Hero from "../components/Hero";
import Gallery from "../components/Gallery";
import Location from "../components/Location";
import News from "./noticias";
import About from "../components/About";

import useScrollSmooth from "../hooks/useScrollSmooth";

export default function Home({ latestPosts, sports }) {
  const router = useRouter();

  useEffect(() => {
    let params = router.query;
    params.scrollTo && setTimeout(() => useScrollSmooth("#contacto"), 1500);
  }, []);

  return (
    <div>
      <Head>
        <title>Club Náutico Zaragoza</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Hero />
        <About link={true} />
        <Gallery images={sports} />
        <News posts={latestPosts} loadMore={false} />
        <Location />
      </main>
    </div>
  );
}

export async function getStaticProps() {
  const res = await fetch(
    `${process.env.NEXT_PUBLIC_BASEURL}/api/posts?populate=*&pagination[pageSize]=3&sort[0]=publishedAt%3Adesc`
  );
  const resSports = await fetch(
    `${process.env.NEXT_PUBLIC_BASEURL}/api/sports?populate=portrait&sort[0]=order&pagination[pageSize]=6`
  );

  const latestPosts = await res.json();
  const sports = await resSports.json();

  return {
    props: {
      latestPosts: latestPosts.data,
      sports: sports.data,
    },
  };
}
